Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.local/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dataDir='/neurodesktop-storage/'
os.chdir(dataDir) # change directories
!datalad install https://github.com/OpenNeuroDatasets/ds004698.git # install NYU retinotopy dataset
os.chdir('/neurodesktop-storage/ds004698/derivatives/freesurfer') # change directories
subject='sub-01'
cmd1=f"""datalad get {subject}/*""" # download all freesurfer files from subject
cmd2=f"""datalad get /neurodesktop-storage/ds004698/derivatives/fmriprep/sub-01/ses-01/func/sub-01_ses-01_task-fixedbar_run-1_space-T1w_*""" #download all preprocessed functional volumes from subject
os.system(cmd1)
os.system(cmd2)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m dataDir[38;5;241m=[39m[38;5;124m'[39m[38;5;124m/neurodesktop-storage/[39m[38;5;124m'[39m
[0;32m----> 2[0m [43mos[49m[38;5;241;43m.[39;49m[43mchdir[49m[43m([49m[43mdataDir[49m[43m)[49m [38;5;66;03m# change directories[39;00m
[1;32m      3[0m get_ipython()[38;5;241m.[39msystem([38;5;124m'[39m[38;5;124mdatalad install https://github.com/OpenNeuroDatasets/ds004698.git # install NYU retinotopy dataset[39m[38;5;124m'[39m)
[1;32m      4[0m os[38;5;241m.[39mchdir([38;5;124m'[39m[38;5;124m/neurodesktop-storage/ds004698/derivatives/freesurfer[39m[38;5;124m'[39m) [38;5;66;03m# change directories[39;00m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/neurodesktop-storage/'

